---
name: test_rule2
description: test rule
enabled: true

trigger:
  type: polling_sesnor.example_trigger

criteria:
  trigger.data.rule:
    type: "equals"
    pattern: "rule2"
action:
  ref: polling_sesnor.send_email
  parameters:
    data: "{{ trigger.payload_schema }}"
